name: HQC_128_1_CCA2
type: kem
claimed-nist-level: 1
claimed-security: IND-CCA2
length-public-key: 3125
length-ciphertext: 6234
length-secret-key: 3165
length-shared-secret: 64
nistkat-sha256: # TODO
principal-submitters:
  - Carlos Aguilar Melchor
  - Nicolas Aragon
  - Slim Bettaieb
  - Loïc Bidoux
  - Olivier Blazy
  - Jean-Christophe Deneuville
  - Philippe Gaborit
  - Edoardo Persichetti
  - Gilles Zémor
auxiliary-submitters: # None
implementations:
    - name: leaktime
      version: http://pqc-hqc.org/doc/hqc-reference-implementation_2019-04-10.zip
